"use client"

import { MasonryGallery } from "./masonry-gallery"

const portfolioItems = [
  {
    id: "hero-1",
    type: "hero" as const,
    src: "/aurora-mountains-cinematic.png",
    alt: "ComfyUI专业作品集",
    title: "专注 ComfyUI 生成与工作流设计",
    subtitle: "展示成品图、节点流程与可复用的 workflow",
    description: "深度探索ComfyUI的无限可能，分享高质量的AI生成作品与实用工作流",
    badge: "持续更新",
    cta: "查看作品",
    href: "/works",
  },
  {
    id: "work-1",
    type: "image" as const,
    src: "/medical-dashboard-blue.png",
    alt: "人像风格化作品",
    title: "人像风格化作品",
    category: "ComfyUI 成品",
    tech: ["LoRA", "ControlNet", "SDXL"],
    year: "2025",
    href: "/works/portrait-stylization",
    badge: "成品",
  },
  {
    id: "workflow-1",
    type: "video" as const,
    src: "/placeholders/flow-demo.mp4",
    poster: "/glowing-astronaut.png",
    alt: "多ControlNet构图工作流演示",
    title: "多ControlNet构图工作流",
    category: "ComfyUI 工作流",
    tech: ["ControlNet", "OpenPose", "Canny", "Depth"],
    year: "2025",
    href: "/workflows/multi-controlnet",
    badge: "工作流",
    isWorkflow: true,
  },
  {
    id: "work-2",
    type: "image" as const,
    src: "/mobile-shopping-app.png",
    alt: "商业产品摄影",
    title: "商业产品摄影",
    category: "ComfyUI 成品",
    tech: ["产品摄影", "Depth", "专业光影"],
    year: "2025",
    href: "/works/product-photography",
    badge: "成品",
  },
  {
    id: "workflow-2",
    type: "image" as const,
    src: "/financial-dashboard-dark.png",
    alt: "批量处理工作流",
    title: "批量处理工作流",
    category: "ComfyUI 工作流",
    tech: ["批量处理", "自动化", "效率"],
    year: "2025",
    href: "/workflows/batch-processing",
    badge: "工作流",
    isWorkflow: true,
  },
  {
    id: "work-3",
    type: "image" as const,
    src: "/luxury-restaurant-branding.png",
    alt: "奇幻风景创作",
    title: "奇幻风景创作",
    category: "ComfyUI 成品",
    tech: ["奇幻", "概念艺术", "风景"],
    year: "2025",
    href: "/works/fantasy-landscape",
    badge: "成品",
  },
  {
    id: "workflow-3",
    type: "video" as const,
    src: "/placeholders/inpaint-demo.mp4",
    poster: "/educational-platform-interface.png",
    alt: "智能修复工作流演示",
    title: "智能修复工作流",
    category: "ComfyUI 工作流",
    tech: ["Inpainting", "修复", "编辑"],
    year: "2025",
    href: "/workflows/inpainting",
    badge: "工作流",
    isWorkflow: true,
  },
  {
    id: "work-4",
    type: "image" as const,
    src: "/ai-writing-assistant-interface.png",
    alt: "角色设计作品",
    title: "角色设计作品",
    category: "ComfyUI 成品",
    tech: ["角色设计", "Reference", "一致性"],
    year: "2025",
    href: "/works/character-design",
    badge: "成品",
  },
  {
    id: "workflow-4",
    type: "image" as const,
    src: "/music-streaming-app.png",
    alt: "风格迁移工作流",
    title: "风格迁移工作流",
    category: "ComfyUI 工作流",
    tech: ["风格迁移", "艺术化", "创意"],
    year: "2025",
    href: "/workflows/style-transfer",
    badge: "工作流",
    isWorkflow: true,
  },
  {
    id: "work-5",
    type: "image" as const,
    src: "/real-estate-crm-dashboard.png",
    alt: "电影级场景生成",
    title: "电影级场景生成",
    category: "ComfyUI 成品",
    tech: ["电影级", "场景", "渲染"],
    year: "2024",
    href: "/works/cinematic-scenes",
    badge: "成品",
  },
]

export function ContentGrid() {
  return (
    <div className="max-w-[1360px] mx-auto px-6 md:px-10">
      <MasonryGallery items={portfolioItems} />
    </div>
  )
}
